[package]
name = "mmu-native"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.9"
hermit-sync = "0.1.6"
constants = { path = "../constants", default-features = false }
address = { path = "../address", default-features = false }
abstractions = { path = "../abstractions", default-features = false }
mmu-abstractions = { path = "../mmu-abstractions" }
allocation-abstractions = { path = "../allocation-abstractions", default-features = false }
platform-specific = { path = "../platform-specific", default-features = false }

[features]
default = []
riscv64 = []
loongarch64 = []
