[package]
name = "address"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
constants = { path = "../constants" }
abstractions = { path = "../abstractions", default-features = false }
platform-specific = { path = "../platform-specific", default-features = false }

[features]
default = ["no_std"]
std = []
no_std = []