name: Install riscv64-linux-musl-cc and loongarch64-linux-musl-cc toolchain

runs:
  using: composite
  steps:

# RISC-V 64
  - name: Attempt to restore toolchain from cache
    id: cache-rv
    uses: actions/cache@v4
    with:
      path: riscv64-linux-musl-cross
      key: riscv64-musl-cache
      restore-keys: |
        riscv64-musl-

  - name: Download musl toolchain
    if: steps.cache-rv.outputs.cache-hit != 'true'
    shell: bash
    run: |
      wget https://github.com/neuq-rcore/testsuit-binary/releases/download/riscv64/riscv64-linux-musl-cross.tgz
      tar -xf riscv64-linux-musl-cross.tgz

  - name: Cache sdcard.img if not cached
    if: steps.cache-rv.outputs.cache-hit != 'true'
    uses: actions/cache@v4
    with:
      path: riscv64-linux-musl-cross
      key: riscv64-musl-cache

# Loongarch 64
  - name: Attempt to restore toolchain from cache
    id: cache-la
    uses: actions/cache@v4
    with:
      path: loongarch64-linux-musl-cross
      key: loongarch64-musl-cache
      restore-keys: |
        loongarch64-musl-
  
  - name: Download musl toolchain
    if: steps.cache-la.outputs.cache-hit != 'true'
    shell: bash
    run: |
      wget https://github.com/LoongsonLab/oscomp-toolchains-for-oskernel/releases/download/loongarch64-linux-musl-cross-gcc-13.2.0/loongarch64-linux-musl-cross.tgz
      tar -xf loongarch64-linux-musl-cross.tgz
  
  - name: Cache sdcard.img if not cached
    if: steps.cache-la.outputs.cache-hit != 'true'
    uses: actions/cache@v4
    with:
      path: loongarch64-linux-musl-cross
      key: loongarch64-musl-cache
  
  - name: Add toolchian to PATH
    shell: bash
    run: |
      echo "$PWD/riscv64-linux-musl-cross/bin" >> $GITHUB_PATH
      echo "$PWD/loongarch64-linux-musl-cross/bin" >> $GITHUB_PATH

  - name: Verify installation
    shell: bash
    run: |
      riscv64-linux-musl-cc --version
      loongarch64-linux-musl-cc --version
