[package]
name = "allocation-abstractions"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
address = { path = "../address", default-features = false }

[features]
default = ["no_std"]
std = []
no_std = []
