[package]
name = "runtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
paste = "1.0.15"
hermit-sync = "0.1.6"
runtime-macros = { path = "../runtime-macros", optional = true }
utilities = { path = "../utilities" }

[build-dependencies]
serde_json = "1.0"

[target.'cfg(target_arch = "riscv64")'.dependencies]
riscv = "0.12"
sbi-rt = "0.0.3"

[features]
default = []

# Whether the Rust's standard library is available.
# If disabled, and the std crate is available, the std crate is used.
# Otherwise, the core crate, alloc and some custom implementations are used to simulate the std crate
no_std = []

# This feature should only be used by rust binary crates.
# for example, the kernel crate.
binary_crate = ["boot"]
boot = ["runtime-macros"]
