name: Sync to GitLab

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # 获取所有历史记录以便完整同步
          fetch-depth: 0
      
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Preprocess documents
        run: | 
          bash .github/gitlab-prerun.sh

          git add .
          git commit -m "Sync from GitHub"

      - name: Push to GitLab
        env:
          GITLAB_URL: ${{ vars.GITLAB_URL }}
          GITLAB_USER: ${{ vars.GITLAB_USER }}
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          # 添加GitLab远程仓库
          git remote add gitlab $GITLAB_URL
          
          # 使用token进行身份验证的URL
          GITLAB_URL_WITH_AUTH=$(echo $GITLAB_URL | sed "s|https://|https://$GITLAB_USER:$GITLAB_TOKEN@|")
          
          # 更新remote URL以包含认证信息
          git remote set-url gitlab $GITLAB_URL_WITH_AUTH
          
          # 推送所有分支和标签到GitLab
          git push --force --all gitlab
          git push --force --tags gitlab
